# Generated by Django 5.1.2 on 2024-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(help_text='Data de admissão na empresa', verbose_name='Admissão'),
        ),
    ]
