# Generated by Django 5.1.2 on 2024-11-06 17:59

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_data_admissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
