# Generated by Django 5.1.2 on 2024-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do servico', max_length=100, unique=True, verbose_name='nome')),
                ('preco', models.CharField(help_text='Preço do servico', max_length=5, verbose_name='preco')),
                ('descricao', models.TextField(help_text='Descricao e observacoes do servico', max_length=300, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
