# Generated by Django 5.1.2 on 2024-10-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('produtosservico', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='produtosservico.ProdutosServico', to='produtos.produto'),
        ),
    ]
